CREATE TABLE Book (
	BookID INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	Title VARCHAR(255),
	Author VARCHAR(255),
	PublishDate DATE,
	ISBN VARCHAR(255),
	PRIMARY KEY(BookID)
);


CREATE TABLE Users (
	UserID INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	Name VARCHAR(255),
	Email VARCHAR(255),
	PRIMARY KEY(UserID)
);


CREATE TABLE Checkouts (
    CheckoutID INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    BookID INTEGER NOT NULL,
    UserID INTEGER NOT NULL,
    CheckoutDate DATE,
    ReturnDate DATE,
    PRIMARY KEY(CheckoutID),
    FOREIGN KEY (BookID) REFERENCES Book(BookID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);