services:
  postgres:
    image: postgres:15-alpine  # 官方镜像，推荐固定版本
    container_name: postgres
    environment:
      POSTGRES_USER: zzh0u  # 替换为你的用户名
      POSTGRES_PASSWORD: 123456  # 替换为强密码
      POSTGRES_DB: postgres  # 替换为你的数据库名
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped     # 自动重启策略

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API 端口（用于客户端访问）
      - "9001:9001"  # 控制台端口（Web 管理界面）
    volumes:
      - ./storage/minio:/data  # 挂载数据目录（持久化存储）
    environment:
      - MINIO_ROOT_USER=zzh0u      # 管理员用户名
      - MINIO_ROOT_PASSWORD=123456789  # 管理员密码（至少8位）
      - TZ=Asia/Shanghai  # 设置时区
    command: server /data --console-address ":9001"  # 启动命令
    restart: unless-stopped  # 容器退出时自动重启
